#!/usr/bin/env python3
"""Bastard D.I.Y. Excuse Board

http://bofh.bjash.com/ExcuseBoard.html
"""
import random

ADJECTIVE = [
    "aborted",
    "asynchronous",
    "bidirectional",
    "delayed",
    "deprecated",
    "dereferenced",
    "dual-homed",
    "duplicated",
    "dynamic",
    "extraneous",
    "fatal",
    "generic",
    "illegal",
    "immediate",
    "inherent",
    "insufficient",
    "intermittent",
    "invalid",
    "legacy",
    "localised",
    "logic",
    "major",
    "migrated",
    "minor",
    "multiple",
    "multiplexed",
    "nonfatal",
    "non-replicated",
    "non-serious",
    "non-specific",
    "non-static",
    "non-valid",
    "nullified",
    "outmoded",
    "partial",
    "permanent",
    "redundant",
    "replicated",
    "resignalled",
    "serial",
    "serious",
    "static",
    "synchronous",
    "temporary",
    "total",
    "undetermined",
    "undiagnosable",
    "unfiltered",
    "unregistered",
    "unreplicatable",
    "unreportable",
    "unsupported",
    "unvalidated",
    "viral",
    "virtual",
    "void",
]

NOUN_1 = [
    "array",
    "assessment",
    "authentication",
    "backplane",
    "bus",
    "checksum",
    "code",
    "comms",
    "configuration",
    "decryption",
    "encryption",
    "environmental",
    "execution",
    "file",
    "firewall",
    "firmware",
    "framing",
    "gateway",
    "handler",
    "hardware",
    "initialisation",
    "installation",
    "integrity",
    "interpretation",
    "library",
    "loading",
    "logic-subsystem",
    "media",
    "memory",
    "metadata",
    "operation",
    "paging",
    "parameter",
    "parity",
    "peripheral",
    "pointer",
    "precondition",
    "programming",
    "protocol",
    "proxy",
    "reception",
    "registry",
    "request",
    "resource",
    "retrieval",
    "runtime",
    "service",
    "software",
    "stack",
    "streaming",
    "subsystem",
    "swapfile",
    "synchronisation",
    "syntax",
    "systems",
    "timing",
    "topology",
    "transmission",
]

NOUN_2 = [
    "anomaly",
    "bug",
    "condition",
    "corruption",
    "crash",
    "crashdump",
    "dereferencing",
    "deprecation",
    "destabilisation",
    "destruction",
    "desynchronisation",
    "dump",
    "exhaustion",
    "expiry",
    "failure",
    "fault",
    "halt",
    "incompatibility",
    "infection",
    "interrupt",
    "interruption",
    "invalidation",
    "lockout",
    "nmi",
    "outage",
    "overflow",
    "override",
    "problem",
    "reclock",
    "rejection",
    "seizure",
    "stackdump",
    "timeout",
    "unavailability",
    "underflow",
]

LEVEL = ["error", "flag", "problem", "signal", "warning"]


def _bofh():
    """Generate a random BOFH excuse"""
    return [
        random.choice(ADJECTIVE),
        random.choice(NOUN_1),
        random.choice(NOUN_2),
        random.choice(LEVEL),
    ]


def bofh():
    """Generate a random BOFH excuse and format it for display"""
    return " ".join([w.capitalize() for w in _bofh()])


def main():
    """BOFH console entrypoint"""
    print(bofh())
